spring:
  datasource:
    url: jdbc:mysql://localhost:3360/wechat?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hyde
    password: hyde
  mvc:
    view:
      prefix: /
      suffix: .html
  application:
    name: wmis
  profiles:
    include: env
    active: dev
  resources:
    chain:
      html-application-cache: false


