spring:
  datasource:
    url: jdbc:mysql://localhost:3360/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hyde
    password: hyde

  devtools:
    restart:
      additional-paths: src/main/java